Feature/main/create type components logos techs
m-ret/gexpsoftware pull request #10
Opened 2023-04-20 07:57 UTC by jasc66

Se crea carrucel para logos de tecnologias

2023-04-20 08:12 UTC, m-ret requested changes

2023-04-20 08:12 UTC, m-ret commented on components/Brands/index.tsx
>                    Trus by
Trust By

2023-04-20 08:12 UTC, m-ret commented on components/Video/index.tsx
>  const Video = () => {
Si el componente ya no tiene un video o si no es de un vide, no se debería de llamar video. Póngale un nombre más descriptivo.

2023-04-20 08:12 UTC, m-ret commented on components/Video/index.tsx
> +</div>*/}
Hay que dejar de comentar el código y pensar en algo para no hacerlo más. Porque sino vamos a terminar con un montón de código comentado y es una mala práctica. Sin embargo por ahorita lo dejamos así, pero hay que pensar en algo. Hay que definir mejor si se van a necesitar luego esos componentes o no.

Una idea sería crear branches específicos tipo: Se removió X parte del código.
Entonces luego cuando necesitamos esas partes del código, volvemos a al branch y recuperamos el código y lo usamos de nuevo.

2023-04-20 08:12 UTC, m-ret commented on components/Video/index.tsx
> +const codesData: Code[] = [
Esto mejor se debería de llamar `techStack`

2023-04-20 08:12 UTC, m-ret commented on components/Video/index.tsx
Todo esta parte tiene que cambiarla porque el componente ya no es un video, ahora aquí veo que se guarda algo que se llama `SingleCode`, debería de ser `TechStack`.

2023-04-20 08:12 UTC, m-ret commented on components/Video/index.tsx
> +const codesData: Code[] = [
Esta variable, sáquela de aquí y la mueve a un file: `constants.ts`.

Y hace:

`export const TechStackData: Code[] = [...]`

2023-04-20 08:12 UTC, m-ret commented on components/Video/index.tsx
> +    id: 1,
Estos ids también puede crearlos con este hook: https://react.dev/reference/react/useId en algún momento quizá lo necesite.

2023-04-20 08:12 UTC, m-ret commented on components/Video/index.tsx
> +const SingleCode = ({ code }: { code: Code }) => {
Este componente debería estar en otro file también. Dentro del mismo folder, pero por separado. Cuando le toque hacer unit testing me lo va a agradecer.

2023-04-20 08:14 UTC, m-ret commented on types/code.ts
> +
Use esto en VsCode para evitar esto: https://stackoverflow.com/a/54270768

2023-04-21 03:17 UTC, jasc66 commented on components/Brands/index.tsx
>                    Trus by
Listo 
<h1 className="mb-5 text-2xl text-center font-bold text-black dark:text-white sm:text-3xl">
              Trust By
          </h1>

2023-04-21 03:59 UTC, jasc66 commented on components/Video/index.tsx
>  const Video = () => {
{
    id: 1,
    name: "css",
    image: "/images/techstack/css-3.svg",
  },

2023-04-21 04:00 UTC, jasc66 commented on components/Video/index.tsx
>  const Video = () => {
Se crea nueva carpeta y se cambian las rutas y se limpia el contenido de la anterior

2023-04-21 04:03 UTC, jasc66 commented on components/Video/index.tsx
> +</div>*/}
Al crearse un componente nuevo llamado TechStack se limpia el codigo y se deja solo el necesario.  Pero definitivo toca hacerlo como dices

2023-04-21 04:04 UTC, jasc66 commented on components/Video/index.tsx
![image](https://user-images.githubusercontent.com/33616594/233538312-cb9ce7de-d82b-466e-b446-359ec2dd6b28.png)

2023-04-21 04:05 UTC, jasc66 commented on components/Video/index.tsx
Se renombra como SingleTechStack esto para mantener el estandar usado por la plantilla en otros componentes donde se utilizan, de igual forma me indicas si lo renombro diferente

2023-04-21 04:08 UTC, jasc66 commented on components/Video/index.tsx
> +const codesData: Code[] = [
Esa variable se elimina ya que es esta parte no va ser necesario el modal de igual forma esta disponible en el componente de video, se crea 
![image](https://user-images.githubusercontent.com/33616594/233538718-9317e606-b402-41f4-acff-6dda4282b124.png)

2023-04-21 04:09 UTC, jasc66 commented on components/Video/index.tsx
> +    id: 1,
esos id provienen de los types y son reutilizables cuando se requieran de la siguiente manera 
![image](https://user-images.githubusercontent.com/33616594/233538887-d8cf4dad-e116-4727-9180-dd7bf5897f67.png)

2023-04-21 04:11 UTC, jasc66 commented on components/Video/index.tsx
> +const SingleCode = ({ code }: { code: Code }) => {
estos vienen de los types en este caso solo se llama la imagen y el name 
![image](https://user-images.githubusercontent.com/33616594/233539116-37da5045-42f9-4b46-b45f-663b9f014a6b.png)

2023-04-21 04:12 UTC, jasc66 commented on components/Video/index.tsx
> +const SingleCode = ({ code }: { code: Code }) => {
De igual forma si se puede mejorar me indicas cual sería la forma correcta

2023-04-21 04:13 UTC, jasc66 commented on types/code.ts
> +export type Code = {
export type TechStack = {
    id: number;
    name: string;
    image: string;
  };

2023-04-21 04:14 UTC, jasc66 commented on types/code.ts
> +export type Code = {
Se omite la palabra Type ya que estan dentro de type

2023-04-21 04:17 UTC, jasc66 commented on components/Video/index.tsx
> +const codesData: Code[] = [
![image](https://user-images.githubusercontent.com/33616594/233539694-08ea8baa-826f-46db-a677-be6c5afa1015.png)

Se hace el cambio

2023-04-21 04:17 UTC, jasc66 commented on components/Video/index.tsx
> +const codesData: Code[] = [
![image](https://user-images.githubusercontent.com/33616594/233539757-a7c2cec7-8b32-4203-b0a1-1784941ce8f9.png)

2023-04-22 18:29 UTC, m-ret approved these changes

2023-04-22 18:29 UTC, m-ret commented on components/TechStack/index.tsx
> +const TechStackData: TechStackType[] = [
Inside the TechStack folder, create a new file called `constants.ts`, put this variable there in the `constants.ts` file, then import it to this current file.

2023-04-22 18:29 UTC, m-ret commented on components/TechStack/index.tsx
> +const SingleTechStack = ({ techstack }: { techstack: TechStackType }) => {
Take this component out of here. Create a new file for it with the same name of the component, then call it where you need it.

2023-04-22 18:29 UTC, m-ret commented on components/Video/index.tsx
>  const Video = () => {
This video component should be renamed. Or if we are not using it, just get it delete.

2023-04-24 05:38 UTC, m-ret approved these changes
Ahora si se ve mucho mejor y más limpio todo.

2023-04-24 05:38 UTC, m-ret approved these changes

2023-04-24 05:39 UTC, merged